### ISSUE TITLE
Revive Repo

### ISSUE THREAD

**Issue by JohJakob** [hydrixos/cocoaheads-le#2]
I would like to see this repo revived to include new talks, showcases, and projects (as well as more CocoaHeads Leipzig activity on GitHub in general).

**Comment by hydrixos** [comment]
Thanks for the reminder ;-). I'm sorry that I've let this slide over the past few years. I have just added the talks since 2019. I will also ask whether I can still get some of the slides and sample projects of past talks.

**Comment by hydrixos** [comment]
Closed it after pushing talks since 2019.

**Comment by hydrixos** [comment]
Thanks for the reminder ;-). I'm sorry that I've let this slide over the past few years. I have just added the talks since 2019. I will also ask whether I can still get some of the slides and sample projects of past talks.
